In [ ]:
import pandas as pd

# **BASE DE FORMAS DE PAGAMENTOS**

In [ ]:
df1 = pd.read_excel('/content/vendas_por_forma_pagamento.xls.xltx')
df2 = pd.read_excel('/content/vendas_por_forma_pagamento_1.xls.xltx')
df3 = pd.read_excel('/content/vendas_por_forma_pagamento_2.xls.xltx')

In [ ]:
forma_de_pagamento = pd.concat([df1, df2, df3])

In [ ]:
forma_de_pagamento

   Código      Nome  Quantidade  Valor Pago     Taxa   Faturado
0  212004   Crédito        1148   115440.27  4698.42  110741.85
1  212003    Débito        1280    98338.48  1543.91   96794.57
2  212005       Pix         486    36290.15     0.00   36290.15
3  212002  Dinheiro         565    23980.89     0.00   23980.89
0  212004   Crédito        1687   181972.23  7406.27  174565.96
1  212003    Débito        1580   148254.94  2327.60  145927.34
2  212005       Pix         867    71619.69     0.00   71619.69
3  212002  Dinheiro         506    32179.05     0.00   32179.05
0  212004   Crédito         190    19175.93   780.46   18395.47
1  212003    Débito         117    10246.83   160.88   10085.95
2  212005       Pix          90     7028.24     0.00    7028.24
3  212002  Dinheiro          57     2985.60     0.00    2985.60

In [ ]:
forma_de_pagamento = forma_de_pagamento.groupby(["Código","Nome"], as_index=False).sum()

In [ ]:
forma_de_pagamento

   Código      Nome  Quantidade  Valor Pago      Taxa   Faturado
0  212002  Dinheiro        1128    59145.54      0.00   59145.54
1  212003    Débito        2977   256840.25   4032.39  252807.86
2  212004   Crédito        3025   316588.43  12885.15  303703.28
3  212005       Pix        1443   114938.08      0.00  114938.08

In [ ]:
pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [ ]:
forma_de_pagamento.to_excel("/content/forma_de_pagamento.xlsx", index=False)

# **BASE VENDAS POR PRODUTO**

In [ ]:
df7 = pd.read_excel('/content/vendas_produto.xltx')
df8 = pd.read_excel('/content/vendas_produto_1.xltx')
df9 = pd.read_excel('/content/vendas_produto_2.xltx')

In [ ]:
vendas_produto = pd.concat([df7, df8, df9])

In [ ]:
vendas_produto

,Produto,Categoria,Quantidade,Valor
0,ALCATRAO COM MEL E LIMÃO,CACHAÇASCACHAÇASCACHAÇAS,79,606.94
1,ALMOFADINHA DE QUEIJO GOUDA,0,76,1752.40
2,AMENDOIM COM CHARQUE,BELISCARBELISCARBELISCAR,349,7574.12
3,AMENDOIM TORRADO,0,1,5.00
4,AMSTEL,CERVEJASCERVEJASCERVEJAS,222,2719.13
...,...,...,...,...
222,pastel de camarao,BELISCAR,3,36.00
223,sarapatel executivo,0,1,27.00
224,ÁGUA,OUTRAS BEBIDASOUTRAS BEBIDASOUTRAS BEBIDAS,1278,4990.82
225,ÁGUA COM GÁS,OUTRAS BEBIDASOUTRAS BEBIDASOUTRAS BEBIDAS,512,2524.10
226,ÁGUA DE COCO COPO,OUTRAS BEBIDASOUTRAS BEBIDASOUTRAS BEBIDAS,458,4191.17

In [ ]:
vendas_produto.drop('Codigo', axis=1, inplace=True)

In [ ]:
vendas_produto = vendas_produto.groupby(["Produto"], as_index=False).sum()

In [ ]:
vendas_produto.to_excel("/content/vendas_produto.xlsx", index=False)

# **BASE VENDAS POR MÊS**

In [ ]:
df10 = pd.read_excel('/content/vendas_data.xltx')
df11 = pd.read_excel('/content/vendas_data_1.xltx')
df12 = pd.read_excel('/content/vendas_data_2.xltx')

In [ ]:
vendas_data = pd.concat([df10, df11, df12])

In [ ]:
vendas_data

,Código,Cliente,Valor Total,Acréscimo,Taxas Marketplace,Desconto,Valor Recebido,Forma de Pagamento,Canal,Data,Histórico de vendas de 02/09/2025 até 02/09/2026,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,216457403,Não identificado,1276.3,0.0,0.0,0.0,1276.3,COMPOSTO,PDV,2025-08-30 21:37:59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,216453159,Não identificado,12.0,0.0,0.0,0.0,12.0,Dinheiro,PDV,2025-08-30 21:31:18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,216431278,Não identificado,103.0,0.0,0.0,0.0,103.0,Pix,PDV,2025-08-30 20:56:07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,216417133,Não identificado,755.6,0.0,0.0,0.0,755.6,COMPOSTO,PDV,2025-08-30 20:33:24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,216393314,Não identificado,70.0,0.0,0.0,0.0,70.0,Débito,PDV,2025-08-30 19:51:56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,302489833,Não identificado,39.5,0.0,0.0,0.0,39.5,Pix,PDV,2026-09-03 18:58:15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
406,302467155,Não identificado,28.0,0.0,0.0,0.0,28.0,Crédito,PDV,2026-09-03 17:33:07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407,302442675,Não identificado,73.6,0.0,0.0,0.0,73.6,Crédito,PDV,2026-09-03 15:44:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,302433524,Não identificado,13.0,0.0,0.0,0.0,13.0,Débito,PDV,2026-09-03 14:59:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,Total,NaN,39484.6,58.0,0.0,48.0,39436.6,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
vendas_data = vendas_data.groupby(["Data"], as_index=False).sum()

In [ ]:
vendas_data.to_excel("/content/vendas_data.xlsx", index=False)